### ISSUE TITLE
RDF, instead of  cavexml:map-link , use bibo:Map

### ISSUE THREAD

**Issue by jmvanel** [nschorgh/CaveXML#3]
Another improvement for CaveXML in RDF is to use instead of  `cavexml:map-link` , `bibo:Map` from Bibo ontology :
https://bibliontology.com/

**Comment by nschorgh** [comment]
Okay. Is this the right declaration?
`declare namespace bibo="http://purl.org/ontology/bibo/" `

My map-link tag is also meant to include URIs to digital cave survey data, but none of my records actually includes one of those yet, so it will be fine. (I don't know which is the wiser decision: only have graphical maps for map-link, have graphical and digital maps, or have no dedicated map-link tag separate from the reference tag at all.)

**Comment by jmvanel** [comment]
Yes it would be the correct declaration in xquery .
BUT , I made a wrong recommendation !
`bibo:Map` is defined as a class, not a property .

Instead we can use:
https://schema.org/hasMap

So, replace 
```xquery
    { local:processTag( $rec/map-link, "cavexml:map-link" ) }
```
with 
```xquery
    { local:processTag( $rec/map-link, "schema:hasMap" ) }
```

**Comment by nschorgh** [comment]
Done.
